In [1]:
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data_Bantuan.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print (X)

[['losari' 40 'tani']
 ['kajoran' 45 'kebun']
 ['kragan' 50 'kebun']
 ['losari' 50 'tani']
 ['kajoran' 42 'tani']
 ['kragan' 40 'buruh']
 ['losari' 36 'buruh']
 ['kajoran' 35 'buruh']
 ['kragan' 36 'tani']
 ['losari' 45 'kebun']
 ['kajoran' 20 'kebun']
 ['losari' 40 'tani']
 ['kajoran' 45 'kebun']
 ['kragan' 50 'kebun']
 ['losari' 50 'tani']
 ['kajoran' 42 'tani']
 ['kragan' 40 'buruh']
 ['losari' 36 'buruh']
 ['kajoran' 35 'buruh']
 ['kragan' 36 'tani']
 ['losari' 45 'kebun']
 ['kajoran' 20 'kebun']]


In [7]:
print (y)

['Belum' 'Sudah' 'Sudah' 'Belum' 'Belum' 'Sudah' 'Belum' 'Sudah' 'Belum'
 'Sudah' 'Sudah' 'Belum' 'Sudah' 'Sudah' 'Belum' 'Belum' 'Sudah' 'Belum'
 'Sudah' 'Belum' 'Sudah' 'Sudah']


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 2])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print (X)

[[0.0 0.0 1.0 0.0 0.0 1.0 40]
 [1.0 0.0 0.0 0.0 1.0 0.0 45]
 [0.0 1.0 0.0 0.0 1.0 0.0 50]
 [0.0 0.0 1.0 0.0 0.0 1.0 50]
 [1.0 0.0 0.0 0.0 0.0 1.0 42]
 [0.0 1.0 0.0 1.0 0.0 0.0 40]
 [0.0 0.0 1.0 1.0 0.0 0.0 36]
 [1.0 0.0 0.0 1.0 0.0 0.0 35]
 [0.0 1.0 0.0 0.0 0.0 1.0 36]
 [0.0 0.0 1.0 0.0 1.0 0.0 45]
 [1.0 0.0 0.0 0.0 1.0 0.0 20]
 [0.0 0.0 1.0 0.0 0.0 1.0 40]
 [1.0 0.0 0.0 0.0 1.0 0.0 45]
 [0.0 1.0 0.0 0.0 1.0 0.0 50]
 [0.0 0.0 1.0 0.0 0.0 1.0 50]
 [1.0 0.0 0.0 0.0 0.0 1.0 42]
 [0.0 1.0 0.0 1.0 0.0 0.0 40]
 [0.0 0.0 1.0 1.0 0.0 0.0 36]
 [1.0 0.0 0.0 1.0 0.0 0.0 35]
 [0.0 1.0 0.0 0.0 0.0 1.0 36]
 [0.0 0.0 1.0 0.0 1.0 0.0 45]
 [1.0 0.0 0.0 0.0 1.0 0.0 20]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print (y)

[0 1 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [13]:
print (X_test)

[[0.0 1.0 0.0 0.0 0.0 1.0 36]
 [0.0 1.0 0.0 1.0 0.0 0.0 40]
 [0.0 0.0 1.0 0.0 0.0 1.0 50]
 [0.0 1.0 0.0 0.0 1.0 0.0 50]
 [1.0 0.0 0.0 1.0 0.0 0.0 35]]


In [14]:
print (X_train)

[[1.0 0.0 0.0 0.0 0.0 1.0 42]
 [1.0 0.0 0.0 0.0 1.0 0.0 20]
 [1.0 0.0 0.0 0.0 0.0 1.0 42]
 [0.0 1.0 0.0 0.0 1.0 0.0 50]
 [0.0 0.0 1.0 1.0 0.0 0.0 36]
 [0.0 0.0 1.0 1.0 0.0 0.0 36]
 [1.0 0.0 0.0 1.0 0.0 0.0 35]
 [1.0 0.0 0.0 0.0 1.0 0.0 45]
 [0.0 0.0 1.0 0.0 0.0 1.0 50]
 [0.0 0.0 1.0 0.0 0.0 1.0 40]
 [1.0 0.0 0.0 0.0 1.0 0.0 20]
 [0.0 0.0 1.0 0.0 1.0 0.0 45]
 [0.0 0.0 1.0 0.0 1.0 0.0 45]
 [0.0 1.0 0.0 0.0 0.0 1.0 36]
 [1.0 0.0 0.0 0.0 1.0 0.0 45]
 [0.0 0.0 1.0 0.0 0.0 1.0 40]
 [0.0 1.0 0.0 1.0 0.0 0.0 40]]


In [15]:
print (y_test)

[0 1 0 1 1]


In [16]:
print (y_train)

[0 1 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, -1:] = sc.fit_transform(X_train[:, -1:])
X_test[:, -1:] = sc.transform(X_test[:, -1:])

In [18]:
print (X_test)

[[0.0 1.0 0.0 0.0 0.0 1.0 -0.3898063175990153]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.09213603870522193]
 [0.0 0.0 1.0 0.0 0.0 1.0 1.296991929465815]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.296991929465815]
 [1.0 0.0 0.0 1.0 0.0 0.0 -0.5102919066750746]]


In [19]:
print (X_train)

[[1.0 0.0 0.0 0.0 0.0 1.0 0.33310721685734057]
 [1.0 0.0 0.0 0.0 1.0 0.0 -2.3175757428159645]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.33310721685734057]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.296991929465815]
 [0.0 0.0 1.0 1.0 0.0 0.0 -0.3898063175990153]
 [0.0 0.0 1.0 1.0 0.0 0.0 -0.3898063175990153]
 [1.0 0.0 0.0 1.0 0.0 0.0 -0.5102919066750746]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.6945639840855184]
 [0.0 0.0 1.0 0.0 0.0 1.0 1.296991929465815]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.09213603870522193]
 [1.0 0.0 0.0 0.0 1.0 0.0 -2.3175757428159645]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.6945639840855184]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.6945639840855184]
 [0.0 1.0 0.0 0.0 0.0 1.0 -0.3898063175990153]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.6945639840855184]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.09213603870522193]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.09213603870522193]]
